apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rick-and-morty-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rick-and-morty-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "rick-and-morty-chart.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
